language: java
branches:
  only:
  - master
  - develop
install: true
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/prepare_travis_settings.sh
- $HOME/build-script/travis-ci/gsp-gen.sh -p gsp
- $HOME/build-script/travis-ci/build-nablarch.sh -p development
- $HOME/build-script/travis-ci/upload-test-report.sh -p dev-deploy
notifications:
  slack:
    secure: cX9Wp+b0Pnh94z2smW1Je556WAqjlFqj65U4lGcqg/j6U01iRYIWdvJ93OCbBnH91EiTKVif3OH5i7zH4Kf01e7/LXPW8IU88YC8ANuiFzt5ZICpjnP7ZyQbGgmsOL5GUf3xte12e5P6lumoG5u8jeHDZwA8Azf7nDMWRSTkb5gdzE6F0uWkxZ2oOXD7J9Xkp4XXuSvJgDic+P8NzxqsPI0W5lkmhCuoO96CZrlaXLuFO1J767bRgS5EpDYsbJRfKiIoJ5U5lfG+3AQMY1zpd/yb/KNU/OJAoJqWgyv4xqDLlvAbKXAoC7/E3qppxywmmKt4+3CDVu47sxD47AbNFAfyY9vWKRLFunDqSuQ5iMDoGKRZUceWZ2b3Cl8rfYfsjc6HQHEcgwFRlVtRfO8sZWmxICLHG49DczcxAG30I13WJU9nk74sgPifmHeNUrq+DaRbAufIkrXvck531JfyH5NzV2PE+mOxT7E7OWzKrC1j9qPcAdGBC1gb/CB3jSEhfJK1g5BrMX3mE9kKm2XiyFtIA8a8qZFcW5MCtWUWieJIQ/0xVLugrSQsZKc9Kajp/dz1jTZ2YJeOtliTVnZko9GA9IR428SXxSUtcyIaq9IPLSbJRiL+yuJUfkhNzVMXHpKNX8i+4nFnKn16WDCuk/FDJT5nN0Y2c2s3kmaAGh4=
